name: Deploy Spring BE to EC2

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  build:
    env:
      RDS_HOST: ${{ secrets.RDS_HOST }}
      RDS_PORT: ${{ secrets.RDS_PORT }}
      RDS_NAME: ${{ secrets.RDS_NAME }}
      RDS_USER: ${{ secrets.RDS_USER }}
      RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
      SECURITY_USER_NAME: ${{ secrets.SECURITY_USER_NAME }}
      SECURITY_USER_PASSWORD: ${{ secrets.SECURITY_USER_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
      JWT_REFRESH_TOKEN_EXPIRATION: ${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: playBaseballServer
          path: build/libs/playBaseballServer-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: playBaseballServer
          path: build/libs/

      - name: Deploy to EC2
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/playBaseballServer-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/playBaseballServer.jar
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "pkill -9 java; nohup java -jar /home/${{ secrets.EC2_USER }}/playBaseballServer.jar > app.log 2>&1 &"
          rm -f private_key.pem
